jax:
  use_jax: false                      # If True, uses JAX internally, whereas False uses normal Numpy.
numba:
  cache: false
  nopython: true
  parallel: false
output:
  fit_dill: false
test:
  disable_positions_lh_inversion_check: false
